services:
  db:
    image: postgres:17-alpine
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U \"$${POSTGRES_USER:-app}\" -d \"$${POSTGRES_DB:-appdb}\""]
      interval: 5s
      retries: 10
    restart: unless-stopped

  users:
    image: ghcr.io/rory619/usersservicecicd2/service_users:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
    restart: unless-stopped

  courses:
    image: ghcr.io/rory619/coursesservicecicd2/service_courses:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8000"
    restart: unless-stopped

  bookings:
    image: ghcr.io/rory619/bookingsservicecicd2/service_bookings:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      DATABASE_URL: ${DATABASE_URL}
      SERVICE_A_BASE_URL: ${SERVICE_A_BASE_URL}
      RABBIT_URL: ${RABBIT_URL}
    depends_on:
      db:
        condition: service_healthy
      users:
        condition: service_started
    ports:
      - "8003:8000"
    restart: unless-stopped

  notifications_api:
    image: ghcr.io/rory619/notificationsservicecicd2/service_notifications:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      DATABASE_URL: ${DATABASE_URL}
      RABBIT_URL: ${RABBIT_URL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8004:8000"
    restart: unless-stopped

  notifications_queue_worker:
    image: ghcr.io/rory619/notificationsservicecicd2/service_notifications:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      RABBIT_URL: ${RABBIT_URL}
    depends_on:
      notifications_api:
        condition: service_started
    command: python -u -m app.worker
    restart: unless-stopped

  notifications_order_worker:
    image: ghcr.io/rory619/notificationsservicecicd2/service_notifications:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      RABBIT_URL: ${RABBIT_URL}
    depends_on:
      notifications_api:
        condition: service_started
    command: python -u -m app.order_worker
    restart: unless-stopped

  notifications_payment_worker:
    image: ghcr.io/rory619/notificationsservicecicd2/service_notifications:latest
    env_file: ./.env
    environment:
      APP_ENV: docker
      RABBIT_URL: ${RABBIT_URL}
    depends_on:
      notifications_api:
        condition: service_started
    command: python -u -m app.payment_worker
    restart: unless-stopped

volumes:
  postgres-data: